# Generated by Django 5.1.2 on 2024-10-20 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitetour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['id', 'name', 'surname'], name='sitetour_gu_id_8ab06e_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='sitetour.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='sitetour.guide', verbose_name='Гид'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='sitetour.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='sitetour.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='sitetour.tour', verbose_name='Тур'),
        ),
    ]
