# Generated by Django 5.1.2 on 2024-10-27 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetour', '0003_review_slug_alter_guide_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('WTPM', 'Ожидает оплаты'), ('PAID', 'Оплачено'), ('CANC', 'Отменено')], default='WTPM', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=1500, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 час'), django.core.validators.MaxValueValidator(100, message='максимум 100 часов')], verbose_name='Длительность'),
        ),
        migrations.CreateModel(
            name='LocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='locations', verbose_name='Фото')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sitetour.location')),
            ],
        ),
    ]
