# Generated by Django 5.1.2 on 2025-01-30 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetour', '0005_remove_location_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 звезда'), django.core.validators.MaxValueValidator(5, message='Максимум 5 звезд')], verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='sitetour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='sitetour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_participants',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимум 1 участник'), django.core.validators.MaxValueValidator(100, message='максимум 100 участников')], verbose_name='Максимальное число участников'),
        ),
    ]
