# Generated by Django 5.1.2 on 2025-02-22 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetour', '0006_review_rating_alter_booking_tour_id_alter_guide_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Название'),
        ),
    ]
