# Generated by Django 5.1.2 on 2025-02-26 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetour', '0007_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tour_id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='status',
        ),
        migrations.AddField(
            model_name='tour',
            name='base_max_participants',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Базовое максимальное число участников'),
        ),
        migrations.AddField(
            model_name='tour',
            name='default_duration_hours',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Продолжительность по умолчанию (часов)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('status', models.CharField(choices=[('ACT', 'Активна'), ('CAN', 'Отменена'), ('END', 'Завершена')], default='ACT', max_length=3, verbose_name='Статус')),
                ('max_participants', models.IntegerField(verbose_name='Максимальное число участников')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sitetour.tour', verbose_name='Тур')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='sitetour.toursession', verbose_name='Сессия тура'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='toursession',
            index=models.Index(fields=['start_datetime', 'status'], name='sitetour_to_start_d_8a151e_idx'),
        ),
    ]
