# Generated by Django 5.1.2 on 2025-02-26 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetour', '0008_remove_booking_tour_id_remove_tour_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toursession',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='tour',
            name='max_participants',
            field=models.IntegerField(default=10, verbose_name='Максимальное число участников'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='default_duration_hours',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Продолжительность по умолчанию (часов)'),
        ),
    ]
